# Regresión lineal - SciKit-Learn

Resumen:
+ Regresión lineal con SciKit-Learn

## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [1]:
from sklearn.feature_selection import RFE  # Recursive features elimination
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("./data/ads/Advertising.csv")

In [3]:
feature_cols = ["TV", "Radio", "Newspaper"]
X = data[feature_cols]
Y = data["Sales"]

In [4]:
estimator = SVR(kernel="linear")  # Tipo de modelo a crear: lineal
selector = RFE(estimator, 2, step=1).fit(X, Y)

In [5]:
# Vamos a comprobar la lista de variables seleccionadas
selector.support_

array([ True,  True, False])

Es decir, se seleccionarían TV y Radio, descartándose Newspaper

In [6]:
# Ranking de variables predictoras (las seleccionadas siempre aparecen en ranking 1 y el resto se ordenan por su significatividad para el modelo)
selector.ranking_

array([1, 1, 2])

In [7]:
# Utilizamos la regresión lineal de Scikit-learn
X_pred = X[["TV", "Radio"]]
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
lm.intercept_

2.921099912405138

In [9]:
lm.coef_

array([0.04575482, 0.18799423])

In [10]:
#Valor de R2 ajustado
lm.score(X_pred, Y)

0.8971942610828956